# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'only'

# --- Pengaturan Model ---
model:
  name: 'higgs_4_layer_only_features'
  layers: 4
  neurons: 300
  activation: 'relu'
  input_shape_factor: 7

# --- Pengaturan Pelatihan ---
training:
  optimizer: 'adam'
  loss: 'binary_crossentropy'
  epochs: 100
  batch_size: 2048
  early_stopping_patience: 10

