# configs/exp_1_layer_only_features.yaml
# Menggunakan 1 hidden layer dan fitur tingkat tinggi (only).

# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'only'          # Menggunakan 7 fitur tingkat tinggi

# --- Pengaturan Model ---
model:
  name: 'higgs_1_layer_only_features'
  layers: 1                    # 1 hidden layer
  neurons: 300
  activation: 'relu'
  input_shape_factor: 7        # HARUS 7 karena feature_set adalah 'only'

# --- Pengaturan Pelatihan ---
training:
  optimizer: 'adam'
  loss: 'binary_crossentropy'
  epochs: 100
  batch_size: 2048
  early_stopping_patience: 10

