# configs/exp_1_layer_all_features.yaml
# Menggunakan 1 hidden layer dan semua fitur (all).

# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'all'           # Menggunakan semua 28 fitur

# --- Pengaturan Model ---
model:
  name: 'higgs_1_layer_all_features'
  layers: 1                    # 1 hidden layer
  neurons: 300
  activation: 'relu'
  input_shape_factor: 28       # HARUS 28 karena feature_set adalah 'all'

# --- Pengaturan Pelatihan ---
training:
  optimizer: 'adam'
  loss: 'binary_crossentropy'
  epochs: 100
  batch_size: 2048
  early_stopping_patience: 10

