# configs/exp_4_layers_heavy_laptop.yaml
# Konfigurasi "berat" untuk pengujian akhir di laptop dengan GPU.

# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'all'           # Menggunakan semua 28 fitur
  num_train_samples: 2500000   # Gunakan 2.5 juta sampel untuk latihan
  num_valid_samples: 250000    # Gunakan 250k sampel untuk validasi

# --- Pengaturan Model ---
model:
  name: 'higgs_4_layer_heavy_laptop'
  layers: 4                    # 4 hidden layer, lebih dekat ke paper
  neurons: 300                 # 300 neuron, sesuai paper
  activation: 'relu'
  input_shape_factor: 28       # Sesuaikan dengan feature_set 'all'

# --- Pengaturan Pelatihan ---
training:
  optimizer: 'adam'
  loss: 'binary_crossentropy'
  epochs: 100                  # Biarkan EarlyStopping yang menentukan
  batch_size: 1024
  early_stopping_patience: 10  # Kita bisa lebih sabar karena ini tes yang lebih serius

