# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'high'

# --- Pengaturan Model ---
model:
  name: 'higgs_4_layer_high_features'
  layers: 4
  neurons: 300
  activation: 'relu'
  input_shape_factor: 7

# --- Pengaturan Pelatihan ---
training:
  learning_rate: 0.001 # Learning rate yang umum untuk Adam
  epochs: 100
  batch_size: 2048
  early_stopping_patience: 10

