# configs/exp_3_layers_medium.yaml
# Konfigurasi "medium" untuk pengujian yang lebih berat di laptop dengan GPU.

# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'all'           # Menggunakan semua 28 fitur
  num_train_samples: 1000000   # Gunakan 1 juta sampel untuk latihan
  num_valid_samples: 100000    # Gunakan 100k sampel untuk validasi

# --- Pengaturan Model ---
model:
  name: 'higgs_3_layer_medium'
  layers: 3                    # 3 hidden layer
  neurons: 256                 # Neuron bisa sedikit lebih sedikit dari skala penuh
  activation: 'relu'
  input_shape_factor: 28       # Sesuaikan dengan feature_set 'all'

# --- Pengaturan Pelatihan ---
training:
  optimizer: 'adam'
  loss: 'binary_crossentropy'
  epochs: 50                   # Kita bisa menambah epoch sedikit
  batch_size: 1024             # Ukuran batch yang lebih besar, cocok untuk GPU
  early_stopping_patience: 7   # Sedikit lebih sabar

