# configs/exp_1_layer_raw_features.yaml
# Menggunakan 1 hidden layer dan fitur mentah (raw).

# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'raw'           # Menggunakan 21 fitur mentah sesuai permintaan

# --- Pengaturan Model ---
model:
  name: 'higgs_1_layer_raw_features'
  layers: 1                    # 1 hidden layer sesuai permintaan
  neurons: 300                 # 300 neuron, nilai yang wajar untuk baseline
  activation: 'relu'
  input_shape_factor: 21       # HARUS 21 karena feature_set adalah 'raw'

# --- Pengaturan Pelatihan ---
training:
  optimizer: 'adam'
  loss: 'binary_crossentropy'
  epochs: 100                  # Biarkan EarlyStopping yang menentukan kapan harus berhenti
  batch_size: 2048             # Kita bisa gunakan batch size lebih besar di GPU ini
  early_stopping_patience: 10

