# configs/exp_2_layers_lite.yaml
# Konfigurasi ringan untuk pengujian cepat di laptop.

# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'raw'         # 'raw' (21 fitur) lebih ringan daripada 'all' (28 fitur)
  num_train_samples: 100000  # Hanya gunakan 100k sampel untuk latihan
  num_valid_samples: 20000   # Hanya gunakan 20k sampel untuk validasi

# --- Pengaturan Model ---
model:
  name: 'higgs_2_layer_lite'
  layers: 2                  # Lebih sedikit layer
  neurons: 128               # Lebih sedikit neuron
  activation: 'relu'
  input_shape_factor: 21     # Sesuaikan dengan feature_set 'raw'

# --- Pengaturan Pelatihan ---
training:
  optimizer: 'adam'
  loss: 'binary_crossentropy'
  epochs: 20                 # Lebih sedikit epoch untuk tes cepat
  batch_size: 512            # Ukuran batch yang lebih kecil, ramah untuk VRAM terbatas
  early_stopping_patience: 5

