# configs/exp_4_layers_raw_features.yaml
# Menggunakan 4 hidden layer dan fitur mentah (raw).

# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'raw'           # Tetap menggunakan 21 fitur mentah

# --- Pengaturan Model ---
model:
  name: 'higgs_4_layer_raw_features'
  layers: 4                    # Meningkatkan kompleksitas model menjadi 4 hidden layer
  neurons: 300
  activation: 'relu'
  input_shape_factor: 21       # Tetap 21 karena feature_set adalah 'raw'

# --- Pengaturan Pelatihan ---
training:
  optimizer: 'adam'
  loss: 'binary_crossentropy'
  epochs: 100
  batch_size: 2048
  early_stopping_patience: 10

