# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'raw'

# --- Pengaturan Model ---
model:
  name: 'higgs_4_layer_raw_features'
  hidden_layer_nodes: [512, 256, 128, 64]
  input_shape_factor: 21

# --- Pengaturan Pelatihan ---
training:
  learning_rate: 0.001
  # wieght_decay: 0.0001
  epochs: 100
  batch_size: 2048
  early_stopping_patience: 10

