# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'raw'
  num_train_samples: 100000
  num_valid_samples: 20000

# --- Pengaturan Model ---
model:
  name: 'higgs_pytorch_testing'
  hidden_layer_nodes: [128, 128]
  input_shape_factor: 21

# --- Pengaturan Pelatihan ---
training:
  learning_rate: 0.001
  # weight_decay: 0.0001
  epochs: 100
  batch_size: 512
  early_stopping_patience: 15

